tidy -m aboutdoc.html
tidy -m commandline.html
tidy -m comparedirs.html
tidy -m comparefiles.html
tidy -m configuration.html
tidy -m faq.html
tidy -m filters.html
tidy -m index.html
tidy -m installing.html
tidy -m introdiff.html
tidy -m introduction.html
tidy -m locales.html
tidy -m openpaths.html
tidy -m plugins.html
tidy -m quickstart.html
tidy -m shortcuts.html
tidy -m textencoding.html
tidy -m versioncontrol.html
tidy -m whatsnew22.html
